[options]
addons_path=/workspace/odoo/odoo/addons,/workspace/odoo/addons,/workspace/oca/ecommerce-integration,/workspace/oca/sign,/workspace/oca/dms,/workspace/oca/mis-builder,/workspace/oca/server-brand,/workspace/oca/account-reconcile,/workspace/oca/account-invoice-reporting,/workspace/oca/connector,/workspace/oca/queue,/workspace/oca/commission,/workspace/oca/account-financial-reporting,/workspace/oca/edi-framework,/workspace/oca/credit-control,/workspace/oca/community-data-files,/workspace/oca/account-payment,/workspace/oca/bank-statement-import,/workspace/oca/knowledge,/workspace/oca/contract,/workspace/oca/edi,/workspace/oca/helpdesk,/workspace/oca/bank-payment,/workspace/oca/event,/workspace/oca/reporting-engine,/workspace/oca/server-ux,/workspace/oca/e-commerce,/workspace/oca/clodofy-core,/workspace/oca/clodofy-odoo16,/workspace/oca/account-financial-tools,/workspace/oca/design-themes,/workspace/oca/account-invoicing,/workspace/oca/stock-logistics-warehouse,/workspace/oca/server-tools,/workspace/oca/stock-logistics-workflow,/workspace/oca/l10n-spain,/workspace/oca/partner-contact,/workspace/oca/manufacture,/workspace/oca/management-system
admin_passwd=clodofy
db_host=pgdb
db_user=odoo
db_password=odoo
list_db=True
http_enable=True
http_port=8069
proxy_mode=True
limit_memory_hard=2684354560
limit_memory_soft=2147483648
limit_request=8192
limit_time_cpu=60
limit_time_real=0
limit_time_real_cron=-1
longpolling_port=8072
max_cron_threads=2
translate_modules=['all']
workers=0
server_wide_modules=web,base,integration,integration_woocommerce
# [queue_job]
# channels=root:3
# Especificar la base de datos si tienes problemas con múltiples bases
# db_name=tu_base_de_datos