services:
  odoo-dev:
    container_name: odoo-dev
    # image: mjavint/odoodev:16.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - ../odools.toml:/home/odoo/odools.toml
      - ${ODOO_SERVER}:/workspace/odoo
      # - ${ENTERPRISE_ADDONS}:/workspace/enterprise:ro
      - odoo-data:/var/lib/odoo
    command: sleep infinity
    depends_on:
      - pgdb
    # Los puertos ya no se exponen directamente, nginx los maneja
    expose:
      - "8069"
      - "8071"
      - "8072"
    networks:
      - shared-net

  pgdb:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: pgdb
    volumes:
      - pgdb-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    # ports:
    #   - "5432:5433"
    networks:
      - shared-net

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "8085:80"
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - shared-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - odoo-dev
    networks:
      - shared-net

volumes:
  odoo-data:
  pgdb-data:
  pgadmin-data:

networks:
  shared-net:
    external: true
